### ISSUE TITLE
Produciton grade FUOTA Server by TTI?

### ISSUE THREAD

**Issue by t0mZ4** [elsalahy/test-fuota-server#1]
Hi Mate
thanks for the presentation and for sharing this, we will review the code and try to implement with our solutions.

Are you guys working on a production-grade solution for a Fuota Server as part of the TTI offering?

**Comment by elsalahy** [comment]
Hello there
Happy to help.

Yes it's planned for this year, but please contact us in TTI to able to understand the customer demand for the feature.

**Comment by digidhamu** [comment]
@elsalahy Is there any update on Production Grade FUOTA server release on TTI?

**Comment by elsalahy** [comment]
@digidhamu I left TTI some time ago, please reach out to them for any questions you might have around this.
I can imagine that some progress has been done for this since my departure
CC: @johanstokking
